"use client";
import {useEffect,useMemo,useState}from"react";import{tableApi}from"@/lib/table-api";
type Product={id:string;name:string;description:string|null;price:number;currency:string;available:boolean};type Menu={tableName:string;areaName:string;orderingEnabled:boolean;selfServiceEnabled:boolean;menu:{name:string;categories:{name:string;products:Product[]}[]}};type Order={id:string;state:string;estimatedTotal:number;currency:string;version:number;pickupNumber:string|null};
export function TableOrder(){const[data,setData]=useState<Menu|null>(null);const[cart,setCart]=useState<Record<string,number>>({});const[order,setOrder]=useState<Order|null>(null);const[serviceMode,setServiceMode]=useState<"DINE_IN"|"SELF_SERVICE">("DINE_IN");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{tableApi<Menu>("/api/table/menu").then(setData).catch(e=>setError(e.message));},[]);
 const products=useMemo(()=>data?.menu.categories.flatMap(c=>c.products)??[],[data]);const total=products.reduce((s,p)=>s+(cart[p.id]??0)*p.price,0);
 async function submit(){setBusy(true);setError("");try{const items=Object.entries(cart).filter(([,q])=>q>0).map(([productId,quantity])=>({productId,quantity,notes:null}));const created=await tableApi<Order>("/api/table/orders",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID().replaceAll("-","")},body:JSON.stringify({items,customerNote:null,serviceMode})});setOrder(created);setCart({});}catch(e){setError(e instanceof Error?e.message:"Sipariş oluşturulamadı.");}finally{setBusy(false);}}
 if(error&&!data)return<main className="mx-auto min-h-screen max-w-lg p-5"><h1 className="text-2xl font-black">Masa oturumu açılamadı</h1><p role="alert" className="mt-3 text-red-700">{error}</p></main>;if(!data)return<main className="grid min-h-screen place-items-center">Menü hazırlanıyor…</main>;
 return<main className="mx-auto min-h-screen max-w-2xl px-4 pb-36 pt-5"><header className="rounded-3xl bg-[#17201b] p-5 text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">{data.areaName}</p><h1 className="mt-1 text-3xl font-black">{data.tableName}</h1><p className="mt-1 text-white/65">{data.menu.name}</p></header>
 {order&&<section className="mt-4 rounded-2xl bg-emerald-50 p-4"><p className="font-black">Sipariş alındı · {order.state}</p>{order.pickupNumber&&<p className="mt-2 text-3xl font-black tracking-widest">Teslim no: {order.pickupNumber}</p>}<p className="text-sm text-emerald-800">Tahmini toplam {new Intl.NumberFormat("tr-TR",{style:"currency",currency:order.currency}).format(order.estimatedTotal)}</p></section>}
 {error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}
 {data.menu.categories.map(c=><section key={c.name} className="mt-6"><h2 className="text-xl font-black">{c.name}</h2><div className="mt-3 grid gap-3">{c.products.map(p=><article key={p.id} className="flex items-center justify-between gap-4 rounded-2xl border bg-[#fffdf8] p-4"><div><h3 className="font-black">{p.name}</h3><p className="text-sm text-[#68736b]">{p.description}</p><p className="mt-1 font-bold">{new Intl.NumberFormat("tr-TR",{style:"currency",currency:p.currency}).format(p.price)}</p></div>{data.orderingEnabled&&<div className="flex items-center gap-2"><button aria-label={`${p.name} azalt`} className="min-h-11 min-w-11 rounded-full border" onClick={()=>setCart(v=>({...v,[p.id]:Math.max(0,(v[p.id]??0)-1)}))}>−</button><b>{cart[p.id]??0}</b><button aria-label={`${p.name} artır`} className="min-h-11 min-w-11 rounded-full bg-[#176b52] text-white" onClick={()=>setCart(v=>({...v,[p.id]:(v[p.id]??0)+1}))}>+</button></div>}</article>)}</div></section>)}
 <div className="fixed inset-x-0 bottom-0 border-t bg-[#fffdf8]/95 p-4 backdrop-blur"><div className="mx-auto max-w-2xl">{data.selfServiceEnabled&&<div className="mb-2 grid grid-cols-2 gap-2" aria-label="Servis biçimi"><button className={`min-h-11 rounded-xl border font-bold ${serviceMode==="DINE_IN"?"bg-[#17201b] text-white":""}`} onClick={()=>setServiceMode("DINE_IN")}>Masaya servis</button><button className={`min-h-11 rounded-xl border font-bold ${serviceMode==="SELF_SERVICE"?"bg-[#17201b] text-white":""}`} onClick={()=>setServiceMode("SELF_SERVICE")}>Gel-al / self servis</button></div>}<div className="flex items-center gap-3"><button onClick={()=>tableApi("/api/table/waiter-calls",{method:"POST",body:JSON.stringify({message:"Masa desteği"})}).then(()=>alert("Garson çağrıldı.")).catch(e=>setError(e.message))} className="min-h-12 rounded-xl border px-4 font-bold">Garson çağır</button><button disabled={busy||total<=0||!data.orderingEnabled} onClick={submit} className="min-h-12 flex-1 rounded-xl bg-[#176b52] px-4 font-black text-white disabled:opacity-50">{busy?"Gönderiliyor…":`Sipariş ver · ${new Intl.NumberFormat("tr-TR",{style:"currency",currency:products[0]?.currency??"TRY"}).format(total)}`}</button></div><p className="mt-2 text-center text-xs text-[#68736b]">Gösterilen tutar tahminidir; ödeme/POS veya mali belge değildir.</p></div></div>
 </main>}
