"use client";import{FormEvent,useEffect,useState}from"react";import{api,json}from"@/lib/admin-api";
type Table={id:string;areaId:string;name:string;capacity:number|null;active:boolean};type Area={id:string;name:string;sortOrder:number;active:boolean;tables:Table[]};type QR={tableId:string;exchangeUrl:string;qrPngBase64:string};
export function TableAdmin(){const[areas,setAreas]=useState<Area[]>([]);const[error,setError]=useState("");const[qr,setQr]=useState<QR|null>(null);const refresh=()=>api<Area[]>("/api/admin/tables").then(setAreas).catch(e=>setError(e.message));useEffect(()=>{void refresh()},[]);
 const run=async(fn:()=>Promise<unknown>)=>{try{await fn();await refresh();}catch(e){setError(e instanceof Error?e.message:"İşlem başarısız.")}};
 return<main className="mx-auto min-h-screen max-w-5xl p-5"><a href="/admin" className="font-bold text-[#176b52]">← Panele dön</a><h1 className="mt-4 text-4xl font-black">Alanlar ve masalar</h1><p className="mt-2 text-[#68736b]">QR yenilendiğinde eski kod anında geçersiz olur.</p>{error&&<p className="mt-4 bg-red-50 p-3 text-red-800">{error}</p>}
 <div className="mt-6 grid gap-5 md:grid-cols-2"><section className="rounded-3xl border bg-[#fffdf8] p-5"><h2 className="text-xl font-black">Alan ekle</h2><form className="mt-3 grid gap-3" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void run(()=>api("/api/admin/tables/areas",json("POST",{name:d.get("name"),sortOrder:0})));}}><input name="name" required placeholder="Salon, Teras…" className="min-h-11 rounded-xl border px-3"/><button className="min-h-11 rounded-xl bg-[#176b52] font-bold text-white">Alan ekle</button></form>
 {areas.length>0&&<form className="mt-6 grid gap-3" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void run(async()=>{const result=await api<QR>("/api/admin/tables",json("POST",{areaId:d.get("areaId"),name:d.get("name"),capacity:Number(d.get("capacity"))}));setQr(result);});}}><h2 className="text-xl font-black">Masa ekle</h2><select name="areaId" className="min-h-11 rounded-xl border px-3">{areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><input name="name" required placeholder="Masa 1" className="min-h-11 rounded-xl border px-3"/><input name="capacity" type="number" min="1" max="100" defaultValue="4" className="min-h-11 rounded-xl border px-3"/><button className="min-h-11 rounded-xl bg-[#17201b] font-bold text-white">Masa ve QR oluştur</button></form>}</section>
 <section className="grid content-start gap-4">{areas.map(a=><article key={a.id} className="rounded-3xl border bg-[#fffdf8] p-5"><h2 className="text-xl font-black">{a.name}</h2>{a.tables.map(t=><div key={t.id} className="mt-3 flex items-center justify-between rounded-xl border bg-white p-3"><span className="font-bold">{t.name}</span><button onClick={()=>void run(async()=>setQr(await api<QR>(`/api/admin/tables/${t.id}/rotate`,json("POST"))))} className="min-h-10 rounded-lg border px-3 text-sm font-bold">QR yenile</button></div>)}</article>)}</section></div>
 {qr&&<dialog open className="fixed inset-0 z-50 m-auto max-h-[90vh] w-[min(92vw,30rem)] rounded-3xl border bg-white p-6 shadow-2xl"><h2 className="text-2xl font-black">Yeni masa QR’ı</h2><p className="mt-1 text-sm text-red-700">Bu QR yalnız şimdi gösterilir; güvenli yere kaydedin.</p><img alt="Masa QR" className="mx-auto mt-4 w-full max-w-80" src={`data:image/png;base64,${qr.qrPngBase64}`}/><a download="masa-qr.png" href={`data:image/png;base64,${qr.qrPngBase64}`} className="mt-4 flex min-h-11 items-center justify-center rounded-xl bg-[#176b52] font-bold text-white">PNG indir</a><button onClick={()=>setQr(null)} className="mt-2 min-h-11 w-full rounded-xl border font-bold">Kapat</button></dialog>}
 </main>}
