package com.masaakis.importer.application;

import com.masaakis.addon.application.RequiresAddon;import com.masaakis.security.*;import org.apache.poi.openxml4j.util.ZipSecureFile;import org.apache.poi.ss.usermodel.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;
import java.io.*;import java.math.*;import java.nio.charset.*;import java.util.*;import java.util.zip.*;

@Service public class CatalogProService{
 private static final int MAX_BYTES=5*1024*1024,MAX_ROWS=5000;private final JdbcClient jdbc;public CatalogProService(JdbcClient j){jdbc=j;}
 @RequiresAddon("CATALOG_PRO")@Transactional public ImportView preview(StaffPrincipal p,MultipartFile file)throws IOException{p.require("catalog/write");byte[] bytes=file.getBytes();if(bytes.length==0||bytes.length>MAX_BYTES)throw bad("IMPORT_SIZE","Dosya 1 byte–5 MB olmalı.");String format=format(file.getOriginalFilename(),bytes);String hash=SecurityHashes.sha256(bytes);
  var old=jdbc.sql("select id from catalog_import_job where tenant_id=:t and file_hash=:h").param("t",p.tenantId()).param("h",hash).query(UUID.class).optional();if(old.isPresent())return view(p,old.get());
  List<RowData> rows=format.equals("CSV")?csv(bytes):xlsx(bytes);if(rows.size()>MAX_ROWS)throw bad("IMPORT_ROWS","En fazla 5000 veri satırı yüklenebilir.");UUID id=UUID.randomUUID();int valid=0,errors=0;Set<String>skus=new HashSet<>();
  jdbc.sql("insert into catalog_import_job(id,tenant_id,branch_id,file_hash,format,status,valid_rows,error_rows)values(:id,:t,:b,:h,:f,'PREVIEW',0,0)").param("id",id).param("t",p.tenantId()).param("b",p.branchId()).param("h",hash).param("f",format).update();
  int n=1;for(RowData r:rows){String error=validate(r,skus);boolean ok=error==null;if(ok)valid++;else errors++;jdbc.sql("""
   insert into catalog_import_row(job_id,tenant_id,row_number,category_name,sku,product_name,description,allergens,price,currency,active,available,status,message)
   values(:j,:t,:n,:c,:s,:p,:d,:al,:pr,:cu,:a,:av,:st,:m)
   """).param("j",id).param("t",p.tenantId()).param("n",n++).param("c",trim(r.category,140)).param("s",trim(r.sku,80)).param("p",trim(r.name,180)).param("d",trim(r.description,1000)).param("al",trim(r.allergens,500)).param("pr",r.price).param("cu",upper(r.currency)).param("a",r.active).param("av",r.available).param("st",ok?"VALID":"ERROR").param("m",ok?"Eklenecek":error).update();}
  jdbc.sql("update catalog_import_job set valid_rows=:v,error_rows=:e where id=:id").param("v",valid).param("e",errors).param("id",id).update();return view(p,id);}
 @RequiresAddon("CATALOG_PRO")@Transactional public ImportView commit(StaffPrincipal p,UUID id){p.require("catalog/write");var job=job(p,id);if(job.status.equals("COMMITTED"))return view(p,id);if(job.errors>0)throw conflict("IMPORT_HAS_ERRORS","Hatalı satırlar düzeltilmeden içe aktarılamaz.");UUID menu=jdbc.sql("select id from menu where tenant_id=:t and branch_id=:b order by created_at limit 1").param("t",p.tenantId()).param("b",p.branchId()).query(UUID.class).single();
  var rows=rows(p,id);Map<String,UUID>cats=new HashMap<>();for(var r:rows){UUID category=cats.computeIfAbsent(r.category,x->jdbc.sql("select id from menu_category where tenant_id=:t and menu_id=:m and lower(name)=lower(:n) and archived=false").param("t",p.tenantId()).param("m",menu).param("n",x).query(UUID.class).optional().orElseGet(()->{UUID c=UUID.randomUUID();jdbc.sql("insert into menu_category(id,tenant_id,menu_id,name,sort_order)values(:id,:t,:m,:n,9999)").param("id",c).param("t",p.tenantId()).param("m",menu).param("n",x).update();return c;}));
   jdbc.sql("insert into product(id,tenant_id,category_id,sku,name,description,allergen_info,price,currency,sort_order,active,available) values(:id,:t,:c,:s,:n,:d,:al,:p,:cu,9999,:a,:av)").param("id",UUID.randomUUID()).param("t",p.tenantId()).param("c",category).param("s",empty(r.sku)).param("n",r.name).param("d",empty(r.description)).param("al",empty(r.allergens)).param("p",r.price).param("cu",r.currency).param("a",r.active).param("av",r.available).update();}
  jdbc.sql("update catalog_import_job set status='COMMITTED',committed_at=now() where id=:id").param("id",id).update();return view(p,id);}
 @Transactional(readOnly=true)public byte[] exportCsv(StaffPrincipal p){p.require("read");StringBuilder s=new StringBuilder("sku,category,name,description,price,currency,active,available,allergens\r\n");jdbc.sql("select p.sku,c.name category,p.name,p.description,p.price,p.currency,p.active,p.available,p.allergen_info from product p join menu_category c on c.id=p.category_id and c.tenant_id=p.tenant_id join menu m on m.id=c.menu_id where p.tenant_id=:t and m.branch_id=:b and p.archived=false and c.archived=false order by c.sort_order,p.sort_order").param("t",p.tenantId()).param("b",p.branchId()).query((rs,n)->List.of(cell(rs.getString("sku")),cell(rs.getString("category")),cell(rs.getString("name")),cell(rs.getString("description")),rs.getBigDecimal("price").toPlainString(),rs.getString("currency"),String.valueOf(rs.getBoolean("active")),String.valueOf(rs.getBoolean("available")),cell(rs.getString("allergen_info")))).list().forEach(r->s.append(String.join(",",r)).append("\r\n"));return s.toString().getBytes(StandardCharsets.UTF_8);}
 @RequiresAddon("CATALOG_PRO")@Transactional public BatchView pricePreview(StaffPrincipal p,String mode,BigDecimal value){p.require("price/write");if(!Set.of("SET","ADD","PERCENT").contains(mode)||value==null)throw bad("BULK_PRICE_INVALID","Fiyat işlemi geçersiz.");UUID id=UUID.randomUUID();jdbc.sql("insert into price_change_batch(id,tenant_id,branch_id,status)values(:id,:t,:b,'PREVIEW')").param("id",id).param("t",p.tenantId()).param("b",p.branchId()).update();var products=jdbc.sql("select p.id,p.price,p.version from product p join menu_category c on c.id=p.category_id join menu m on m.id=c.menu_id where p.tenant_id=:t and m.branch_id=:b and p.archived=false").param("t",p.tenantId()).param("b",p.branchId()).query((rs,n)->new PriceBase(rs.getObject("id",UUID.class),rs.getBigDecimal("price"),rs.getLong("version"))).list();for(var x:products){BigDecimal np=switch(mode){case"SET"->value;case"ADD"->x.price.add(value);default->x.price.multiply(BigDecimal.ONE.add(value.divide(BigDecimal.valueOf(100),6,RoundingMode.HALF_UP)));};np=np.setScale(2,RoundingMode.HALF_UP);if(np.signum()<0)throw bad("BULK_PRICE_NEGATIVE","Fiyat negatif olamaz.");jdbc.sql("insert into price_change_item(batch_id,tenant_id,product_id,old_price,new_price,old_version)values(:b,:t,:p,:o,:n,:v)").param("b",id).param("t",p.tenantId()).param("p",x.id).param("o",x.price).param("n",np).param("v",x.version).update();}return batch(p,id);}
 @RequiresAddon("CATALOG_PRO")@Transactional public BatchView priceCommit(StaffPrincipal p,UUID id){p.require("price/write");var b=batch(p,id);if(!b.status.equals("PREVIEW"))return b;for(var x:b.items){int n=jdbc.sql("update product set price=:n,version=version+1,updated_at=now() where id=:p and tenant_id=:t and price=:o and version=:v").param("n",x.newPrice).param("p",x.productId).param("t",p.tenantId()).param("o",x.oldPrice).param("v",x.oldVersion).update();if(n==0)throw conflict("BULK_PRICE_CONFLICT","Bir ürün önizlemeden sonra değişti.");jdbc.sql("update price_change_item set applied_version=:v where batch_id=:b and product_id=:p").param("v",x.oldVersion+1).param("b",id).param("p",x.productId).update();}jdbc.sql("update price_change_batch set status='COMMITTED',committed_at=now() where id=:id").param("id",id).update();return batch(p,id);}
 @RequiresAddon("CATALOG_PRO")@Transactional public BatchView rollback(StaffPrincipal p,UUID id){p.require("price/write");var b=batch(p,id);if(!b.status.equals("COMMITTED")&&!b.status.equals("PARTIAL_ROLLBACK"))return b;int conflicts=0;for(var x:b.items){if("ROLLED_BACK".equals(x.rollbackStatus))continue;int n=jdbc.sql("update product set price=:o,version=version+1,updated_at=now() where id=:p and tenant_id=:t and price=:n and version=:v").param("o",x.oldPrice).param("p",x.productId).param("t",p.tenantId()).param("n",x.newPrice).param("v",x.appliedVersion).update();String status=n==1?"ROLLED_BACK":"CONFLICT";if(n==0)conflicts++;jdbc.sql("update price_change_item set rollback_status=:s where batch_id=:b and product_id=:p").param("s",status).param("b",id).param("p",x.productId).update();}jdbc.sql("update price_change_batch set status=:s,rolled_back_at=now() where id=:id").param("s",conflicts==0?"ROLLED_BACK":"PARTIAL_ROLLBACK").param("id",id).update();return batch(p,id);}
 private ImportView view(StaffPrincipal p,UUID id){var j=job(p,id);return new ImportView(id,j.status,j.valid,j.errors,rows(p,id).stream().map(r->new ImportRow(r.row,r.category,r.sku,r.name,r.price,r.currency,r.message)).toList());}
 private Job job(StaffPrincipal p,UUID id){return jdbc.sql("select status,valid_rows,error_rows from catalog_import_job where id=:id and tenant_id=:t and branch_id=:b").param("id",id).param("t",p.tenantId()).param("b",p.branchId()).query((rs,n)->new Job(rs.getString("status"),rs.getInt("valid_rows"),rs.getInt("error_rows"))).optional().orElseThrow(()->new AppException(HttpStatus.NOT_FOUND,"IMPORT_NOT_FOUND","İçe aktarma bulunamadı."));}
 private List<StoredRow>rows(StaffPrincipal p,UUID id){return jdbc.sql("select row_number,category_name,sku,product_name,description,allergens,price,currency,active,available,message from catalog_import_row where job_id=:j and tenant_id=:t and status='VALID' order by row_number").param("j",id).param("t",p.tenantId()).query((rs,n)->new StoredRow(rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getBigDecimal(7),rs.getString(8),rs.getBoolean(9),rs.getBoolean(10),rs.getString(11))).list();}
 private BatchView batch(StaffPrincipal p,UUID id){String status=jdbc.sql("select status from price_change_batch where id=:id and tenant_id=:t and branch_id=:b").param("id",id).param("t",p.tenantId()).param("b",p.branchId()).query(String.class).optional().orElseThrow(()->new AppException(HttpStatus.NOT_FOUND,"BATCH_NOT_FOUND","Fiyat paketi bulunamadı."));var items=jdbc.sql("select product_id,old_price,new_price,old_version,applied_version,rollback_status from price_change_item where batch_id=:b and tenant_id=:t order by product_id").param("b",id).param("t",p.tenantId()).query((rs,n)->new PriceItem(rs.getObject(1,UUID.class),rs.getBigDecimal(2),rs.getBigDecimal(3),rs.getLong(4),(Long)rs.getObject(5),rs.getString(6))).list();return new BatchView(id,status,items);}
 private static String format(String n,byte[]bytes){String name=n==null?"":n.toLowerCase(Locale.ROOT);boolean zip=bytes.length>4&&bytes[0]=='P'&&bytes[1]=='K';if(name.endsWith(".xlsx")&&zip)return"XLSX";if(name.endsWith(".csv")&&!zip){String head=new String(bytes,0,Math.min(bytes.length,512),StandardCharsets.UTF_8).toLowerCase(Locale.ROOT);if(head.contains("category")&&head.contains("name")&&head.contains("price"))return"CSV";}throw bad("IMPORT_FORMAT","Dosya içeriği ile CSV/XLSX uzantısı eşleşmiyor.");}
 private static List<RowData>csv(byte[]b)throws CharacterCodingException{String text=StandardCharsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).decode(java.nio.ByteBuffer.wrap(b)).toString();String[]ls=text.replace("\r\n","\n").replace('\r','\n').split("\n",-1);if(ls.length<2)return List.of();var h=parse(ls[0]);List<RowData>out=new ArrayList<>();for(int i=1;i<ls.length;i++)if(!ls[i].isBlank())out.add(map(h,parse(ls[i])));return out;}
 private static List<String>parse(String l){List<String>r=new ArrayList<>();StringBuilder s=new StringBuilder();boolean q=false;for(int i=0;i<l.length();i++){char c=l.charAt(i);if(c=='"'){if(q&&i+1<l.length()&&l.charAt(i+1)=='"'){s.append('"');i++;}else q=!q;}else if(c==','&&!q){r.add(s.toString());s.setLength(0);}else s.append(c);}if(q)throw bad("CSV_QUOTES","CSV tırnak yapısı geçersiz.");r.add(s.toString());return r;}
 static List<RowData>xlsx(byte[]b)throws IOException{try(ZipInputStream z=new ZipInputStream(new ByteArrayInputStream(b))){int entries=0;ZipEntry e;while((e=z.getNextEntry())!=null){if(++entries>2000||e.getName().toLowerCase().contains("vbaproject")||e.getName().startsWith("xl/externalLinks"))throw bad("XLSX_UNSAFE","Makro, dış bağlantı veya aşırı arşiv girdisi reddedildi.");}}ZipSecureFile.setMinInflateRatio(.01);try(Workbook w=WorkbookFactory.create(new ByteArrayInputStream(b))){Sheet s=w.getSheetAt(0);if(s.getLastRowNum()>MAX_ROWS)throw bad("IMPORT_ROWS","En fazla 5000 satır.");DataFormatter f=new DataFormatter(Locale.ROOT);List<String>h=cells(s.getRow(0),f);List<RowData>out=new ArrayList<>();for(int i=1;i<=s.getLastRowNum();i++){Row row=s.getRow(i);if(row==null)continue;for(Cell c:row)if(c.getCellType()==CellType.FORMULA)throw bad("XLSX_FORMULA","Formül hücreleri kabul edilmez.");var vals=cells(row,f);if(vals.stream().anyMatch(x->!x.isBlank()))out.add(map(h,vals));}return out;}}
 private static List<String>cells(Row r,DataFormatter f){List<String>x=new ArrayList<>();if(r==null)return x;for(int i=0;i<r.getLastCellNum();i++)x.add(f.formatCellValue(r.getCell(i,Row.MissingCellPolicy.RETURN_BLANK_AS_NULL)));return x;}
 private static RowData map(List<String>headers,List<String>v){Map<String,String>m=new HashMap<>();for(int i=0;i<headers.size();i++)m.put(headers.get(i).trim().toLowerCase(Locale.ROOT),i<v.size()?v.get(i).trim():"");BigDecimal p;try{p=new BigDecimal(m.getOrDefault("price",""));}catch(Exception e){p=null;}return new RowData(m.get("category"),m.get("sku"),m.get("name"),m.get("description"),m.get("allergens"),p,m.getOrDefault("currency","TRY"),bool(m.get("active"),true),bool(m.get("available"),true));}
 private static String validate(RowData r,Set<String>s){if(blank(r.category)||blank(r.name)||r.price==null)return"category, name ve price zorunludur.";if(r.price.signum()<0||r.price.scale()>2)return"Fiyat negatif olamaz ve en fazla 2 ondalık içermeli.";if(!upper(r.currency).matches("[A-Z]{3}"))return"Para birimi üç büyük harf olmalı.";if(!blank(r.sku)&&!s.add(r.sku.toLowerCase(Locale.ROOT)))return"Dosyada yinelenen SKU.";return null;}
 private static boolean bool(String x,boolean d){return blank(x)?d:Set.of("true","1","yes","evet").contains(x.toLowerCase(Locale.ROOT));}private static boolean blank(String x){return x==null||x.isBlank();}private static String trim(String x,int n){return blank(x)?null:x.trim().substring(0,Math.min(n,x.trim().length()));}private static String upper(String x){return x==null?null:x.toUpperCase(Locale.ROOT);}private static String empty(String x){return blank(x)?null:x;}private static String cell(String x){if(x==null||x.isEmpty())return"";String v=Set.of('=','+','-','@').contains(x.charAt(0))?"'"+x:x;return"\""+v.replace("\"","\"\"")+"\"";}private static AppException bad(String c,String m){return new AppException(HttpStatus.BAD_REQUEST,c,m);}private static AppException conflict(String c,String m){return new AppException(HttpStatus.CONFLICT,c,m);}
 record RowData(String category,String sku,String name,String description,String allergens,BigDecimal price,String currency,boolean active,boolean available){}private record Job(String status,int valid,int errors){}private record StoredRow(int row,String category,String sku,String name,String description,String allergens,BigDecimal price,String currency,boolean active,boolean available,String message){}private record PriceBase(UUID id,BigDecimal price,long version){}
 public record ImportRow(int rowNumber,String category,String sku,String name,BigDecimal price,String currency,String message){}public record ImportView(UUID id,String status,int validRows,int errorRows,List<ImportRow>rows){}public record PriceItem(UUID productId,BigDecimal oldPrice,BigDecimal newPrice,long oldVersion,Long appliedVersion,String rollbackStatus){}public record BatchView(UUID id,String status,List<PriceItem>items){}
}
