package com.masaakis.kitchen.application;

import com.masaakis.addon.application.RequiresAddon;import com.masaakis.security.AppException;import com.masaakis.security.StaffPrincipal;
import org.springframework.beans.factory.annotation.Value;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.OffsetDateTime;import java.util.*;
@Service public class KitchenService{private final JdbcClient jdbc;private final String publicBaseUrl;public KitchenService(JdbcClient j,@Value("${app.public-base-url:http://localhost:3000}")String b){jdbc=j;publicBaseUrl=b.replaceAll("/+$","");}
 @Transactional(readOnly=true)public KitchenOverview overview(StaffPrincipal p){p.require("read");String branchSlug=jdbc.sql("select public_slug from branch where id=:id and tenant_id=:tenantId").param("id",p.branchId()).param("tenantId",p.tenantId()).query(String.class).single();
  var stations=jdbc.sql("select id,name,sort_order,active from kitchen_station where tenant_id=:tenantId and branch_id=:branchId order by sort_order,created_at").param("tenantId",p.tenantId()).param("branchId",p.branchId())
   .query((rs,n)->new StationView(rs.getObject("id",UUID.class),rs.getString("name"),rs.getInt("sort_order"),rs.getBoolean("active"),
    jdbc.sql("select category_id from kitchen_station_category where station_id=:id and tenant_id=:tenantId").param("id",rs.getObject("id",UUID.class)).param("tenantId",p.tenantId()).query(UUID.class).list())).list();
  return new KitchenOverview(publicBaseUrl+"/hazir/"+branchSlug,stations);}
 @RequiresAddon("KITCHEN_STATIONS")@Transactional public UUID createStation(StaffPrincipal p,String name,int sort,List<UUID>categoryIds){p.require("table/manage");UUID id=UUID.randomUUID();jdbc.sql("insert into kitchen_station(id,tenant_id,branch_id,name,sort_order)values(:id,:tenantId,:branchId,:name,:sort)").param("id",id).param("tenantId",p.tenantId()).param("branchId",p.branchId()).param("name",name.trim()).param("sort",sort).update();for(UUID c:categoryIds){long count=jdbc.sql("select count(*) from menu_category where id=:id and tenant_id=:tenantId").param("id",c).param("tenantId",p.tenantId()).query(Long.class).single();if(count==0)throw new AppException(HttpStatus.NOT_FOUND,"CATEGORY_NOT_FOUND","Kategori bulunamadı.");jdbc.sql("insert into kitchen_station_category(station_id,tenant_id,category_id)values(:station,:tenantId,:category)").param("station",id).param("tenantId",p.tenantId()).param("category",c).update();}return id;}
 @Transactional(readOnly=true)public List<KitchenItem> queue(StaffPrincipal p,UUID stationId){p.require("read");return jdbc.sql("""
  select oi.id item_id,oi.order_id,oi.product_name_snapshot,oi.quantity,oi.notes,oi.kitchen_state,o.state order_state,o.service_mode,o.pickup_number,t.name table_name,o.submitted_at
  from order_item oi join customer_order o on o.id=oi.order_id and o.tenant_id=oi.tenant_id left join dining_table t on t.id=o.table_id
  where oi.tenant_id=:tenantId and oi.station_id=:stationId and o.branch_id=:branchId and oi.kitchen_state in('QUEUED','PREPARING')
  order by o.submitted_at,oi.created_at
  """).param("tenantId",p.tenantId()).param("stationId",stationId).param("branchId",p.branchId()).query((rs,n)->new KitchenItem(rs.getObject("item_id",UUID.class),rs.getObject("order_id",UUID.class),rs.getString("product_name_snapshot"),rs.getInt("quantity"),rs.getString("notes"),rs.getString("kitchen_state"),rs.getString("order_state"),rs.getString("service_mode"),rs.getString("pickup_number"),rs.getString("table_name"),rs.getObject("submitted_at",OffsetDateTime.class))).list();}
 @RequiresAddon("KITCHEN_STATIONS")@Transactional public void itemState(StaffPrincipal p,UUID itemId,String state){p.require("order/prepare-ready");if(!List.of("PREPARING","DONE").contains(state))throw new AppException(HttpStatus.BAD_REQUEST,"KITCHEN_STATE_INVALID","Mutfak durumu geçersiz.");
  UUID orderId=jdbc.sql("select oi.order_id from order_item oi join customer_order o on o.id=oi.order_id and o.tenant_id=oi.tenant_id where oi.id=:id and oi.tenant_id=:tenantId and o.branch_id=:branchId and oi.station_id is not null").param("id",itemId).param("tenantId",p.tenantId()).param("branchId",p.branchId()).query(UUID.class).optional().orElseThrow(()->new AppException(HttpStatus.NOT_FOUND,"KITCHEN_ITEM_NOT_FOUND","Mutfak kalemi bulunamadı."));
  jdbc.sql("update order_item set kitchen_state=:state where id=:id and tenant_id=:tenantId").param("state",state).param("id",itemId).param("tenantId",p.tenantId()).update();
  if(state.equals("PREPARING"))jdbc.sql("update customer_order set state='PREPARING',version=version+1,updated_at=now() where id=:id and tenant_id=:tenantId and state in('ACCEPTED','PREPARING')").param("id",orderId).param("tenantId",p.tenantId()).update();
  else{long remaining=jdbc.sql("select count(*) from order_item where order_id=:id and tenant_id=:tenantId and kitchen_state<>'DONE'").param("id",orderId).param("tenantId",p.tenantId()).query(Long.class).single();if(remaining==0)jdbc.sql("update customer_order set state=case when service_mode='SELF_SERVICE' then 'READY_FOR_PICKUP' else 'READY' end,version=version+1,updated_at=now() where id=:id and tenant_id=:tenantId and state in('ACCEPTED','PREPARING')").param("id",orderId).param("tenantId",p.tenantId()).update();}}
 @Transactional(readOnly=true)public PickupBoard board(String branchSlug){return jdbc.sql("select id,name from branch where public_slug=:slug and active=true").param("slug",branchSlug).query((rs,n)->new Branch(rs.getObject("id",UUID.class),rs.getString("name"))).optional().map(b->new PickupBoard(b.name,jdbc.sql("select pickup_number,updated_at from customer_order where branch_id=:branch and service_mode='SELF_SERVICE' and state='READY_FOR_PICKUP' order by updated_at limit 50").param("branch",b.id).query((rs,n)->new Pickup(rs.getString("pickup_number"),rs.getObject("updated_at",OffsetDateTime.class))).list())).orElseThrow(()->new AppException(HttpStatus.NOT_FOUND,"BRANCH_NOT_FOUND","Hazır ekranı bulunamadı."));}
 private record Branch(UUID id,String name){}public record StationView(UUID id,String name,int sortOrder,boolean active,List<UUID>categoryIds){}public record KitchenOverview(String publicPickupUrl,List<StationView>stations){}public record KitchenItem(UUID itemId,UUID orderId,String productName,int quantity,String notes,String kitchenState,String orderState,String serviceMode,String pickupNumber,String tableName,OffsetDateTime submittedAt){}public record Pickup(String number,OffsetDateTime readyAt){}public record PickupBoard(String branchName,List<Pickup>ready){}
}
